demo failed due to crash:
    java.lang.IllegalStateException: LifecycleOwner ca.six.router.demo.app.biz.MainActivity@e5708ed is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.